export const GET_KPI_LIST_SUCCESS = "GET_KPI_LIST_SUCCESS"
export const GET_KPI_LIST_STARTED = "GET_KPI_LIST_STARTED"
export const GET_KPI_LIST_FAILURE = "GET_KPI_LIST_FAILURE"

export const GET_rKPI_DATA = "GET_rKPI_DATA"
export const GET_cKPI_DATA = "GET_cKPI_DATA"

export const UPDATE_CURRENT_rKPI_NAME = "UPDATE_CURRENT_rKPI_NAME"
export const UPDATE_CURRENT_cKPI_NAME = "UPDATE_CURRENT_cKPI_NAME"

export const UPDATE_KPI_IS_SELECTED = "UPDATE_KPI_IS_SELECTED"
export const UPDATE_MULTI_SELECT = "UPDATE_MULTI_SELECT"

export const GET_KPI_CATEGORIES_STARTED = "GET_KPI_CATEGORIES_STARTED"
export const GET_KPI_CATEGORIES_SUCCESS = "GET_KPI_CATEGORIES_SUCCESS"
export const GET_KPI_CATEGORIES_FAILURE = "GET_KPI_CATEGORIES_FAILURE"


export const SAVE_UPDATED_R_KPI_SET_STARTED = "SAVE_UPDATED_R_KPI_SET_STARTED"
export const SAVE_UPDATED_R_KPI_SET_SUCCESS = "SAVE_UPDATED_R_KPI_SET_SUCCESS"
export const SAVE_UPDATED_R_KPI_SET_FAILURE = "SAVE_UPDATED_R_KPI_SET_FAILURE"


export const GET_R_KPI_SETS_STARTED = "GET_R_KPI_SETS_STARTED"
export const GET_R_KPI_SETS_SUCCESS = "GET_R_KPI_SETS_SUCCESS"
export const GET_R_KPI_SETS_FAILURE = "GET_R_KPI_SETS_FAILURE"
