export const LOGIN_STARTED = "LOGIN_STARTED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const CREATE_USER_STARTED = "CREATE_USER_STARTED"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

export const LOGOUT = "LOGOUT"

export const GET_USER_INFO_STARTED = "GET_USER_INFO_STARTED"
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE"

export const DELETE_USER_STARTED = "DELETE_USER_STARTED"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE"

export const GET_KPI_LIST_SUCCESS = "GET_KPI_LIST_SUCCESS"
export const GET_KPI_LIST_STARTED = "GET_KPI_LIST_STARTED"
export const GET_KPI_LIST_FAILURE = "GET_KPI_LIST_FAILURE"

export const GET_R_KPI_DATA_STARTED = "GET_R_KPI_DATA_STARTED"
export const GET_R_KPI_DATA_SUCCESS = "GET_R_KPI_DATA_SUCCESS"
export const GET_R_KPI_DATA_FAILURE = "GET_R_KPI_DATA_FAILURE"

export const GET_C_KPI_DATA_STARTED = "GET_C_KPI_DATA_STARTED"
export const GET_C_KPI_DATA_SUCCESS = "GET_C_KPI_DATA_SUCCESS"
export const GET_C_KPI_DATA_FAILURE = "GET_C_KPI_DATA_FAILURE"

export const UPDATE_CURRENT_R_KPI_NAME = "UPDATE_CURRENT_R_KPI_NAME"
export const UPDATE_CURRENT_C_KPI_NAME = "UPDATE_CURRENT_C_KPI_NAME"

export const UPDATE_KPI_IS_SELECTED = "UPDATE_KPI_IS_SELECTED"
export const UPDATE_MULTI_SELECT = "UPDATE_MULTI_SELECT"

export const GET_KPI_CATEGORIES_STARTED = "GET_KPI_CATEGORIES_STARTED"
export const GET_KPI_CATEGORIES_SUCCESS = "GET_KPI_CATEGORIES_SUCCESS"
export const GET_KPI_CATEGORIES_FAILURE = "GET_KPI_CATEGORIES_FAILURE"


export const SAVE_UPDATED_R_KPI_SET_STARTED = "SAVE_UPDATED_R_KPI_SET_STARTED"
export const SAVE_UPDATED_R_KPI_SET_SUCCESS = "SAVE_UPDATED_R_KPI_SET_SUCCESS"
export const SAVE_UPDATED_R_KPI_SET_FAILURE = "SAVE_UPDATED_R_KPI_SET_FAILURE"


export const SAVE_UPDATED_C_KPI_SET_STARTED = "SAVE_UPDATED_C_KPI_SET_STARTED"
export const SAVE_UPDATED_C_KPI_SET_SUCCESS = "SAVE_UPDATED_C_KPI_SET_SUCCESS"
export const SAVE_UPDATED_C_KPI_SET_FAILURE = "SAVE_UPDATED_C_KPI_SET_FAILURE"


export const DELETE_R_KPI_SET_STARTED = "DELETE_R_KPI_SET_STARTED"
export const DELETE_R_KPI_SET_SUCCESS = "DELETE_R_KPI_SET_SUCCESS"
export const DELETE_R_KPI_SET_FAILURE = "DELETE_R_KPI_SET_FAILURE"

export const DELETE_C_KPI_SET_STARTED = "DELETE_C_KPI_SET_STARTED"
export const DELETE_C_KPI_SET_SUCCESS = "DELETE_C_KPI_SET_SUCCESS"
export const DELETE_C_KPI_SET_FAILURE = "DELETE_C_KPI_SET_FAILURE"
