module.exports = [
  {
    name: "Cold climate",
    created: Math.ceil(new Date().getTime()/1000),
    lastUpdated: Math.ceil(new Date().getTime()/1000),
    owner: "Private",
    description: "A set of KPIs for buildings built before 1980 and in a temperated location.",
    values: [
      {name: "Energy need", value: 1500, weight: 1},
      {name: "Energy use", value: 3000, weight: 1},
      {name: "Energy generation", value: 4000, weight: 1},
      {name: "Delivered energy", value: 2000, weight: 1},
      {name: "Exported energy", value: 1000, weight: 1},
      {name: "Self consumption", value: 70, weight: 1},
      {name: "Self generation", value: 50, weight: 1},
      {name: "Yearly net load profile", value: 1600, weight: 1}, 
      {name: "Yearly net load profile", value: 1300, weight: 1}, 
      {name: "Net load duration curve", value: 1100, weight: 1}, 
      {name: "Peak load", value: 2500, weight: 1}, 
      {name: "Peak export", value: 500, weight: 1}, 
      {name: "Utilisation factor", value: 1200, weight: 1}, 
      {name: "Daily net load profile", value: 1300, weight: 1}, 
      {name: "Total gas emissions", value: 1550, weight: 1}, 
      {name: "Total gas emissions pr. m^2", value: 1600, weight: 1}, 
      {name: "Greenhouse gas emissions", value: 1580, weight: 1}, 
      {name: "Life cycle cost", value: 400, weight: 1}, 
      {name: "Life cycle cost pr. m^2", value: 200, weight: 1},
      {name: "Mode of transport", value: 3200, weight: 1},
      {name: "Access to public transport", value: 2400, weight: 1},
      {name: "Number of services, facilities and amenities", value: 800, weight: 1},
      {name: "Meters from services, facilities and amenities", value: 1420, weight: 1},
    ]
  },
  {
    name: "Warm climate",
    created: Math.ceil(new Date().getTime()/1000),
    lastUpdated: Math.ceil(new Date().getTime()/1000),
    owner: "Shared",
    description: "Another nice and useful set of KPIs.",
    values: [
      {name: "Energy need", value: 1200, weight: 1},
      {name: "Energy use", value: 8000, weight: 1},
      {name: "Energy generation", value: 1000, weight: 1},
      {name: "Delivered energy", value: 9000, weight: 1},
      {name: "Exported energy", value: 3000, weight: 1},
      {name: "Self consumption", value: 10, weight: 1},
      {name: "Self generation", value: 90, weight: 1},
      {name: "Yearly net load profile", value: 1900, weight: 1}, 
      {name: "Yearly net load profile", value: 1800, weight: 1}, 
      {name: "Net load duration curve", value: 1100, weight: 1}, 
      {name: "Peak load", value: 1120, weight: 1}, 
      {name: "Peak export", value: 1130, weight: 1}, 
      {name: "Utilisation factor", value: 700, weight: 1}, 
      {name: "Daily net load profile", value: 800, weight: 1}, 
      {name: "Total gas emissions", value: 900, weight: 1}, 
      {name: "Total gas emissions pr. m^2", value: 1000, weight: 1}, 
      {name: "Greenhouse gas emissions", value: 1100, weight: 1}, 
      {name: "Life cycle cost", value: 1200, weight: 1}, 
      {name: "Life cycle cost pr. m^2", value: 1300, weight: 1},
      {name: "Mode of transport", value: 1400, weight: 1},
      {name: "Access to public transport", value: 1500, weight: 1},
      {name: "Number of services, facilities and amenities", value: 1600, weight: 1},
      {name: "Meters from services, facilities and amenities", value: 1700, weight: 1},
    ]
  }
]
